name: say hello

on:
  push:
    branches:
      - main

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello
        run: |
          echo "Hello, World!"
      - name: echo dir
        run: ls -l
      - name: echo pwd
        run: pwd
